# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20160206_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='userprofile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userName',
        ),
    ]
